### PR TITLE
Data driven keybindings: WIP

### PR DESCRIPTION
**Pull request by VisenDev**
Creating a draft pr for easier collaboration

### CODE REVIEW

**Comment by VisenDev** [comment]
@neurocyte would you like me to implement a keybinding configuration system or leave that for a later PR? I figured that you probably would have some preferences for how keybindings would be configured

A few considerations
- Should all keybindings be loaded at runtime - or should some keybindings be builtin (ie, compiled into the executable)
- How should runtime keybindings be stored: lua, json, toml..?
- If some keybindings will be builtin should they be configured in zig or should they be configured in the same way as runtime keybindings?
- In the configuration system, should a sequence of KeyEvents be structured analogously to the zig `KeyEvent` struct, or should a sequence of KeyEvents be represented in a more human friendly manner (ie `<C-x><C-c>`)

**Comment by VisenDev** [comment]
For the moment I've added a super simple text based keybinding parser based on vimscript (Mostly because it makes it a lot easier to specify keybindings when testing)

example:
```vimscript
<F10> open_help
<C-p> open_recent_files
<C-x><C-c> force_quit
j cursor_down
k cursor_up
<Tab> indent
<S-Tab> unindent
```

**Comment by VisenDev** [comment]
Demo of what a lua based keybinding configuration system might look like

```lua
Bindings = {
    ["vim"] = {
        ["normal"] = {
            ["no_match_behavior"] = "ignore",
            ["bindings"] = {
                {"j", "cursor_down"},
                {"k", "cursor_up"},
                {"h", "cursor_left_vim"},
                {"l", "cursor_right_vim"},
                {"i", "mode_change", "insert"},
                {"F2", "namespace_cycle"},
                {":", "open_command_palette"},
            }
        }
        ["insert"] = {
            ["no_match_behavior"] = "insert",
            ["bindings"] = {
                {"<C-c", "mode_change", "normal"},
                {"jk", "mode_change", "normal"},
                {"F2", "namespace_cycle"},
            }
        }
    },
    ["emacs"] = {
        ["base"] = {
            ["no_match_behavior"] = "insert",
            ["bindings"] = {
                {"<C-n>", "cursor_down"},
                {"<C-p>", "cursor_up"},
                {"<C-f>", "cursor_left"},
                {"<C-b>", "cursor_right"},
                {"<C-x><C-c>", "quit"},
                {"<C-x><C-s>", "save"},
                {"<A-x>", "open_command_palette"}
            }
        }
    }
    
}
```

**Comment by neurocyte** [comment]
I have added a build option `-Ddynamic_keybind` to enable the data driven keybindings code so this PR can be merged without breaking anything else.

**Pull request merged**
